# Generated by Django 4.0.3 on 2022-03-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0005_alter_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(db_index=True, max_length=240)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangochat.room')),
            ],
        ),
    ]
