# Generated by Django 4.0.3 on 2022-03-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Romm',
            new_name='Room',
        ),
    ]
